package dialect

import (
	"fmt"
	"strings"

	"dbgold/datamigrate/coldefault"
	"dbgold/datamigrate/source"
	"dbgold/datamigrate/typemap"
)

// DaMengDialect 实现达梦(Oracle 兼容模式)目标库的 SQL 生成。
//
// 与 PostgreSQL 的主要差异:
//   - 自增列用 IDENTITY 在建表时声明(GENERATED BY DEFAULT AS IDENTITY,
//     允许显式插入原 id),而非 Phase3 创建序列。
//   - 不支持 DROP TABLE IF EXISTS:建表 DDL 含独立 DROP 语句,由 Writer 容错执行。
//   - 索引/外键不支持 IF NOT EXISTS;外键不支持 ON UPDATE 子句。
//   - 对象 owner 即所在 schema,无 ALTER ... OWNER TO。
type DaMengDialect struct{}

// NewDaMeng 创建达梦方言。
func NewDaMeng() *DaMengDialect { return &DaMengDialect{} }

func (d *DaMengDialect) Name() string { return "dameng" }

func (d *DaMengDialect) Caps() Capabilities {
	return Capabilities{
		UsesSequences:       false, // 自增用 IDENTITY,不建独立序列
		IdentityInsert:      true,  // 写入含自增列的表需 SET IDENTITY_INSERT
		SupportsDistribute:  false,
		SupportsChangeOwner: false,
	}
}

func (d *DaMengDialect) QuoteIdent(name string) string {
	return fmt.Sprintf(`"%s"`, name)
}

func (d *DaMengDialect) QualifyTable(schema, table string) string {
	if schema == "" {
		return fmt.Sprintf(`"%s"`, table)
	}
	return fmt.Sprintf(`"%s"."%s"`, schema, table)
}

func (d *DaMengDialect) MapType(col source.ColumnInfo, srcType string, opt TypeOpt) string {
	if m, ok := typemap.Get(srcType, "dameng"); ok {
		return m(col, opt.CharInLength, opt.UseNvarchar2)
	}
	return strings.ToUpper(col.DataType)
}

// CreateTableStatements 生成达梦建表 DDL:
//   - 独立 DROP TABLE 语句(无 IF EXISTS,Writer 容错)
//   - CREATE TABLE,自增列追加 IDENTITY(1,1)(种子由 Phase3 reseed 修正)
func (d *DaMengDialect) CreateTableStatements(schema string, info *source.TableDDLInfo, srcType string, opt TypeOpt, name NameFunc) ([]Statement, error) {
	var cols []string
	for _, col := range info.Columns {
		dmType := d.MapType(col, srcType, opt)
		colDef := fmt.Sprintf(`"%s" %s`, name(col.Name), dmType)
		if col.Extra == "auto_increment" {
			// 达梦 Oracle 兼容模式自增列:允许显式插入(导入原 id),种子先填 1
			colDef += " IDENTITY(1, 1)"
		}
		if !col.IsNullable {
			colDef += " NOT NULL"
		}
		if col.Default != nil && col.Extra != "auto_increment" {
			if clause := d.columnDefaultClause(coldefault.Strip(srcType, *col.Default)); clause != "" {
				colDef += clause
			}
		}
		cols = append(cols, "  "+colDef)
	}
	qn := d.QualifyTable(schema, name(info.TableName))
	// 达梦 DROP 不支持 IF EXISTS,且需 CASCADE CONSTRAINTS 清除外键依赖,
	// 否则被其他表外键引用的表无法 DROP(残留旧表导致重建报"已存在")。
	dropSQL := fmt.Sprintf(`DROP TABLE %s CASCADE CONSTRAINTS`, qn)
	createSQL := fmt.Sprintf("CREATE TABLE %s (\n%s\n)", qn, strings.Join(cols, ",\n"))
	return []Statement{{SQL: dropSQL}, {SQL: createSQL}}, nil
}

// columnDefaultClause 生成达梦列默认值子句(含前导空格),无默认值返回空串。
func (d *DaMengDialect) columnDefaultClause(def string) string {
	if def == "" {
		return ""
	}
	upper := strings.ToUpper(strings.TrimSpace(def))
	// 函数/关键字默认值:达梦兼容形式
	switch upper {
	case "CURRENT_TIMESTAMP", "NOW()":
		return " DEFAULT CURRENT_TIMESTAMP"
	case "CURRENT_DATE":
		return " DEFAULT CURRENT_DATE"
	case "CURRENT_TIME":
		return " DEFAULT CURRENT_TIME"
	case "NULL":
		return " DEFAULT NULL"
	case "TRUE":
		return " DEFAULT 1"
	case "FALSE":
		return " DEFAULT 0"
	}
	// MySQL 位串字面量 b'0' → 裸数字 0
	if len(def) >= 3 && (def[0] == 'b' || def[0] == 'B') && def[1] == '\'' && def[len(def)-1] == '\'' {
		inner := def[2 : len(def)-1]
		// 位串转十进制由达梦隐式处理,这里直接给数字字面量
		return fmt.Sprintf(" DEFAULT %d", bitsToInt(inner))
	}
	// 其余函数调用(以右括号结尾)不加引号
	if strings.HasSuffix(upper, ")") {
		return fmt.Sprintf(" DEFAULT %s", def)
	}
	// 普通字面量:加单引号并转义
	return fmt.Sprintf(" DEFAULT '%s'", strings.ReplaceAll(def, "'", "''"))
}

// bitsToInt 把位串(如 "0"/"1"/"101")转为十进制整数。
func bitsToInt(bits string) int64 {
	var n int64
	for _, c := range bits {
		n <<= 1
		if c == '1' {
			n |= 1
		}
	}
	return n
}
